{
 "title": "PostgreSQL Observability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node", "label": "Noeud", "query": { "query": "label_values(pg_static, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability",
     "type": "stat",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_up", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Version",
     "type": "table",
     "gridPos": { "h": 6, "w": 7, "x": 8, "y": 9 },
     "targets": [
      { "expr": "pg_static" }
     ]
    },
    {
     "title": "Alerts",
     "type": "table",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 9 },
     "targets": [
      { "expr": "ALERTS" }
     ]
    }
   ]
  },
  {
   "title": "Native Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 10 },
     "repeat": "node",
     "options": {
      "content": "<center> <h1 style=\"text-transform: capitalize;\">${node} </h1></center>"
     }
    },
    {
     "title": "Connexions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "repeat": "node",
     "targets": [
      {
       "expr": "pg_stat_activity_count{job=\"$node\"}",
       "legendFormat": "{{datname}} {{state}}"
      }
     ]
    },
    {
     "title": "Verrou",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "repeat": "node",
     "targets": [
      {
       "expr": "pg_locks_count{job=\"$node\"}",
       "legendFormat": "{{mode}} sur {{datname}}"
      }
     ]
    },
    {
     "title": "Checkpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "repeat": "node",
     "targets": [
      {
       "expr": "rate(pg_stat_bgwriter_checkpoints_timed{job=\"$node\"}[15s]) > 0",
       "legendFormat": "Scheduled Checkpoint"
      }
     ]
    },
    {
     "title": "Tuples activity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "repeat": "node",
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_deleted{job=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tuples deleted on {{datname}} "
      },
      {
       "expr": "rate(pg_stat_database_tup_inserted{job=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tuples inserted on {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_tup_updated{job=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tuples updated on {{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "repeat": "node",
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{job=\"$node\",datname!=\"\"}[$__rate_interval])",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 7 },
     "targets": [
      { "expr": "node_load1", "legendFormat": "Load 1m" },
      { "expr": "node_load5", "legendFormat": "Load 5m" },
      { "expr": "node_load15", "legendFormat": "Load 15m" }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_Buffers_bytes + node_memory_Cached_bytes",
       "legendFormat": "Cache"
      },
      { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
     ]
    },
    {
     "title": "Battery",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_power_supply_capacity{power_supply=\"BAT0\"}",
       "legendFormat": "{{power_supply}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "repeat": "node",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_database_size_bytes{job=\"$node\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag (from primary)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "pg_replication_replay_lag", "legendFormat": "{{client_addr}}" }
     ]
    },
    {
     "title": "Replication Lab (from replica)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pg_replication_replag{job!=\"primary\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "XLOG Position",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "hex" } },
     "targets": [
      { "expr": "pg_xlog_position", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "XLOG Diff",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "max(pg_xlog_position) - min(pg_xlog_position)"
      },
      { "expr": "1000000000", "legendFormat": "Alert" }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "repeat": "node",
   "targets": [
    {
     "expr": "pg_client_connections_count{job=\"$node\"}",
     "legendFormat": "{{appname}} @ {{client_addr}} on {{datname}}"
    },
    {
     "expr": "pg_settings_max_connections{job=\"$node\"}",
     "legendFormat": "Max Connections"
    }
   ]
  }
 ]
}